spring:
  application:
    name: ribbon
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
 
ribbon:
  MaxAutoRetriesNextServer: 2   #表示访问一个不通后继续向后访问两台
  MaxAutoRetries: 1             #单台服务器重试次数
  OkToRetryOnAllOperations: true      #表示所有请求都重试